# This github-Evennia workflow will build the docs.

name: documentation

on:
  push:
    branches: [ master, develop ]
    paths:
      - 'docs/**'
  pull_request:
    branches: [ master, develop ]
    paths:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install doc-building dependencies
        run: |
          python -m pip install --upgrade pip
          cd docs/
          make install

      # fail early here
      - name: Quick-test docs (no autodocs)
        run: |
          cd docs/
          make quick

      # full game dir needed for mv-local
      - name: Set up evennia game dir
        run: |
          pip install -e .
          cd ..
          evennia --init gamedir
          cd gamedir
          evennia migrate

      - name: Deploy docs (only from master/develop branch)
        if: ${{ github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'}}
        run: |
          git config --global user.email "docbuilder@evennia.com"
          git config --global user.name "Doc builder mechanism"
          cd docs
          make mv-local
          echo "Would deploy here!"
