# This github-Evennia workflow will build the docs.

name: documentation

on:
  push:
    branches: [ master, develop ]
    paths:
      - 'docs/**'
  pull_request:
    branches: [ master, develop ]
    paths:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install doc-building dependencies
        run: |
          python -m pip install --upgrade pip
          cd docs/
          make install

      ## fail early here, run quickstrict with aborts also on warnings
      #- name: Quick-test docs (no autodocs)
      #  run: |
      #    cd docs/
      #    make quickstrict

      # full game dir needed for mv-local
      - name: Set up evennia game dir
        run: |
          pip install -e .
          pip install -r requirements_extra.txt
          cd ..
          evennia --init gamedir
          cd gamedir
          evennia migrate

      - name: Build and deploy docs (only from master/develop branch)
        if: ${{ github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'}}
        run: |
          git fetch origin develop
          git fetch origin v0.9.5
          git config --global user.email "docbuilder@evennia.com"
          git config --global user.name "Evennia docbuilder action"
          cd docs
          make release
